spring:
  profiles:
    active: dev

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  devtools:
    livereload:
      enabled: true